/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package búsquedabinariajframe;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Scrappy Doo Coco
 */
public class ArchivoTextoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaBinariaJFrame
     */
    public ArchivoTextoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        TítuloBúsquedaBinaria = new javax.swing.JLabel();
        Títulodesarrollador = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setText("Guardar Número a Buscar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Generar Números");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("Guardar Archivo");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        TítuloBúsquedaBinaria.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TítuloBúsquedaBinaria.setText("Búsqueda Binaria");

        Títulodesarrollador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Títulodesarrollador.setText("Desarrollado por Isaac Haro");

        lbl1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl1.setText("Ingrese el número que desea buscar:");

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        btn4.setText("Leer Archivo y Hacer la Búsqueda Binaria");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista de números");

        jLabel2.setText("Resultados");

        jScrollPane2.setViewportView(jList2);

        btn5.setText("Guardar Resultados");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3)
                        .addGap(391, 391, 391)
                        .addComponent(btn5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(26, 26, 26)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TítuloBúsquedaBinaria)
                    .addComponent(Títulodesarrollador)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TítuloBúsquedaBinaria)
                .addGap(29, 29, 29)
                .addComponent(Títulodesarrollador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(btn5))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        try {
            get_num_busqueda();
            JOptionPane.showMessageDialog(null, "Digito Guardado");
            System.out.println(get_num_busqueda());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la Búsqueda Binaria, ingrese un dato valido" + e);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(","));
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            guardardatosl1(fichero);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        genera_archivo_texto();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(","));
        int resultado = fileChooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            BusquedaBinaria busquedabin = new BusquedaBinaria();
            if (busquedabin.lectura_archivo(fichero, get_num_busqueda()) == (-1)) {
                modelo.addElement("No se encontro el número " + get_num_busqueda() + " en el archivo seleccionado\n");
            } else {
                modelo.addElement("Se encontro el número " + get_num_busqueda() + " en " + busquedabin.lectura_archivo(fichero, get_num_busqueda()) + " interacciones\n");
            }
            getjList2().setModel(getModelo());
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(","));
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            guardardatosl2(fichero);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchivoTextoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchivoTextoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchivoTextoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchivoTextoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchivoTextoJFrame().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TítuloBúsquedaBinaria;
    private javax.swing.JLabel Títulodesarrollador;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel modelo = new DefaultListModel();

    public void genera_archivo_texto() {
        Random random = new Random();
        for (int i = 0; i < 300; i++) {
            modelo.addElement(random.nextInt(300) + "\n");
        }
        getjList1().setModel(getModelo());
    }

    public void guardardatosl1(File f) {
        FileWriter archivo;
        BufferedWriter filtrado;
        String contenido = "";
        try {
            archivo = new FileWriter(f);
            filtrado = new BufferedWriter(archivo);
            for (int i = 0; i < 300; i++) {
                contenido = jList1.getModel().getElementAt(i).toString();
                filtrado.write(contenido, 0, contenido.length());
            }
            filtrado.flush();
            filtrado.close();
            archivo.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en escritura de archivo" + e);
        }
    }

    private void guardardatosl2(File f) {
        FileWriter archivo;
        BufferedWriter filtrado;
        String contenido = "";
        try {
            archivo = new FileWriter(f);
            filtrado = new BufferedWriter(archivo);
            for (int i = 0; i < jList2.getModel().getSize(); i++) {
                contenido = jList2.getModel().getElementAt(i).toString();
                filtrado.write(contenido, 0, contenido.length());
            }
            filtrado.flush();
            filtrado.close();
            archivo.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en escritura de archivo" + e);
        }
    }

    public DefaultListModel getModelo() {
        return modelo;
    }

    public JList<String> getjList1() {
        return jList1;
    }

    public JList<String> getjList2() {
        return jList2;
    }

    public int get_num_busqueda() {
        return Integer.parseInt(txt1.getText());
    }
}

class BusquedaBinaria extends javax.swing.JFrame {

    public int ordenamiento_y_busqueda_binaria(ArrayList<String> listabb, int b) {

        int[] array = new int[listabb.size()];
        for (int i = 0; i < listabb.size(); i++) {
            array[i] = Integer.parseInt(listabb.get(i));
        }
        Arrays.sort(array);
        //Busqueda Binaria
        ArchivoTextoJFrame archiv = new ArchivoTextoJFrame();
        int centro, primero = 0, ultimo = array.length - 1, valorcentro, cont = 0;
        //Bucle While Busqueda Binaria
        while (primero <= ultimo) {
            centro = (primero + ultimo) / 2;
            valorcentro = array[centro];
            cont++;
            if (b == valorcentro) {
                try {
                    Connection conexion;
                    Statement prep;
                    String respuesta = "insert into interacciones values('"+cont+"','El digito se encontro')";
                    DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                    conexion = DriverManager.getConnection("jdbc:derby://localhost:1527/BusquedaBinaria");
                    prep = conexion.createStatement();
                    prep.executeUpdate(respuesta);
                } catch (SQLException ex) {
                    Logger.getLogger(NewClass.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "El digito " + b + " se encontro en " + cont + " pasos");
                return cont;
            } else if (b < valorcentro) {
                ultimo = centro - 1;
            } else {
                primero = centro + 1;
            }
        }
        JOptionPane.showMessageDialog(null, "El elemento no se encontro");
        //Conexion a la BASE DE DATOS

        return -1;
    }

    public int lectura_archivo(File f, int busq) {
        FileReader archivo;
        BufferedReader filtrado;
        try {
            archivo = new FileReader(f);
            filtrado = new BufferedReader(archivo);
            String linea = "";
            ArrayList<String> listabb = new ArrayList<>();
            for (int i = 0; (linea = filtrado.readLine()) != null; i++) {
                listabb.add(linea);
            }
            archivo.close();
            filtrado.close();
            return ordenamiento_y_busqueda_binaria(listabb, busq);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la lectura del archivo" + e);

        }
        return 0;
    }
}
